[[filter]]
query = "to:your_activity@noreply.github.com"
archive = true
read = true

[[filter]]
query = "from:notifications@github.com LGTM"
label = "github/LGTM"

[[filter]]
query = """
(-to:team_mention@noreply.github.com \
(from:(notifications@github.com) AND (@jfrazelle OR @jessfraz OR to:mention@noreply.github.com OR to:author@noreply.github.com OR to:assign@noreply.github.com)))
"""
label = "participating/github"

[[filter]]
query = """
to:team_mention@noreply.github.com \
-to:mention@noreply.github.com \
-to:author@noreply.github.com \
-to:assign@noreply.github.com
"""
archive = true
read = true

[[filter]]
query = "(from:me AND to:reply@reply.github.com)"
label = "participating/github"

[[filter]]
query = "(from:notifications@github.com)"
label = "github"

[[filter]]
queryOr = [
"to:acm@jessfraz.com",
"to:ACM-W-PUBLIC@listserv.acm.org"
]
label = "Tech Things/ACM"

[[filter]]
queryOr = [
"to:plans@tripit.com"
"to:receipts@concur.com"
"to:plans@concur.com"
"to:receipts@expensify.com"
"to:distribution+managers@dockerproject.org"
"to:organizers+managers@maintainerati.org"
]
delete = true

[[filter]]
queryOr = [
"from:notifications@docker.com"
"from:noreply@github.com"
"to:gandi@jessfraz.com"
"from:no-reply@alertsp.chase.com"
"from:team@mint.com"
"from:support@rackspace.com"
"from:builds@circleci.com"
"from:notify@jessfraz.com"
"from:jenkins@jessfraz.com"
"from:watchtower@jessfraz.com"
"from:checkup@jessfraz.com"
"from:support@tripit.com"
"from:nas@jessfraz.com"
"to:nas@jessfraz.com"
"to:racked@jessfraz.com"
"from:auto-confirm@amazon.com"
"from:shipment-tracking@amazon.com"
"from:orders@eat.seamless.com"
"from:orders@instacart.com"
"from:no-reply@postmates.com"
"from:expiry@letsencrypt.org"
"from:do_not_reply@itunes.com"
"from:digital-no-reply@amazon.com"
"from:no-reply@slack.com"
"from:billing@mailgun.net"
"from:payments-noreply@google.com"
"from:notify@keybase.io"
"from:uber.us@uber.com"
"from:no-reply@alertsp.chase.com"
"from:googlealerts-noreply@google.com"
"from:no-reply@opentable.com"
"from:hello@aspergerexperts.com"
"from:grvfh@aol.com"
"from:onlinebanking@ealerts.bankofamerica.com"
"from:noreply@backup.api.rackspacecloud.com"
"from:gogo@e.gogoair.com"
"from:googlestore-noreply@google.com"
"from:notifications@n.massdrop.com"
"from:no-reply-aws@amazon.com"
"from:donotreply@rxorder.walgreens.com"
"from:ChaseDoNotReply@transunion.com"
"from:RapidRewards@luv.southwest.com"
"from:venmo@venmo.com"
"from:billpay@billpay.bankofamerica.com"
"from:ConEd-bill@emailconed.com"
"from:noreply@mail.bloombergbusiness.com"
"from:no_reply@email.apple.com"
"from:gsuite-noreply@google.com"
"from:no-reply@accounts.google.com"
"from:order-update@amazon.com"
"from:support@flycleaners.com"
"from:mailgun@jessfraz.com"
"from:DeltaAirLines@e.delta.com"
"from:opsgenie@opsgenie.net"
"from:medteam@onemedical.com"
"from:no-reply@dropbox.com"
]
label = "to-be-deleted"

[[filter]]
query = "drive-shares-noreply@google.com OR (subject:\"Invitation to comment\" AND from:me ) OR from:(*@docs.google.com)"
label = "to-be-deleted"

[[filter]]
query = "(from:(-me) {filename:vcs filename:ics} has:attachment) OR (subject:(\"invitation\" OR \"accepted\" OR \"tentatively accepted\" OR \"rejected\" OR \"updated\" OR \"canceled event\" OR \"declined\") when where calendar who organizer)"
label = "to-be-deleted"

[[filter]]
queryOr = [
"list:oss-security@lists.openwall.com"
"list:fulldisclosure@seclists.org"
"list:maintainers@dockerproject.org"
"list:debian-security-announce@lists.debian.org"
"list:docker-maint@lists.alioth.debian.org"
"list:debian-women@lists.debian.org"
"list:debian-dug-nyc@lists.debian.org"
"list:programming@linuxchix.org"
"list:mailman@linuxchix.org"
"list:golang-devexp@googlegroups.com"
"list:tor-dev@lists.torproject.org"
"list:tor-announce@lists.torproject.org"
"list:tor-meeting@lists.torproject.org"
"list:linux-kernel-announce@vger.kernel.org"
"list:dev@opencontainers.org"
"list:security-dev@chromium.org"
"list:golang-announce@googlegroups.com"
"list:golang-dev@googlegroups.com"
"list:go-package-management@googlegroups.com"
"list:dev@lists.clearlinux.org"
"list:kubernetes-security-announce@googlegroups.com"
"list:kubernetes-security@googlegroups.com"
"list:kubernetes-security-discuss@googlegroups.com"
"list:security@kubernetes.io"
"list:security-discuss-private@kubernetes.io"
"list:security-release-team@kubernetes.io"
"list:syzkaller@googlegroups.com"
"list:kubernetes-dev@googlegroups.com"
"list:kubernetes-maintainers@googlegroups.com"
"list:kubernetes-announce@googlegroups.com"
"list:kubernetes-distributors-announce@googlegroups.com"
"list:kubernetes-sig-node@googlegroups.com"
"list:kubernetes-sig-auth@googlegroups.com"
"list:kubernetes-wg-multitenancy@googlegroups.com"
"list:cncf-toc@lists.cncf.io list:security@kubernetes.io"
"list:kubernetes-sig-architecture@googlegroups.com"
"list:kubernetes-wg-container-identity@googlegroups.com"
]
label = "participating/mailing-list"
toMe = true

[[filter]]
query = "list:kubernetes-security-announce@googlegroups.com"
label = "Mailing Lists/kubernetes-security-announce"

[[filter]]
queryOr = [
"list:kubernetes-security@googlegroups.com"
"list:kubernetes-security-discuss@googlegroups.com"
"list:security-discuss-private@kubernetes.io"
"list:security-release-team@kubernetes.io"
"list:security@kubernetes.io"
]
label = "Mailing Lists/kubernetes-security"

[[filter]]
query =
